version: "3.9"

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nextjs
      MYSQL_DATABASE: habit_tracker
      TZ: Europe/Warsaw
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: ~
