version: "3.9"

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nextjs
      MYSQL_DATABASE: habit_tracker
      TZ: Europe/Warsaw
    volumes:
      - mysql:/var/lib/mysql

  migrate:
    build:
      context: .
      target: db-migrator
    environment:
      DATABASE_URL: mysql://root:nextjs@db:3306/habit_tracker?connection_timeout=300
    depends_on:
      - db

  app:
    platform: "linux/amd64"
    build:
      context: .
    working_dir: /app
    networks: [ proxy, default ]
    image: habit-tracker
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:nextjs@db:3306/habit_tracker
      NEXT_PUBLIC_API_URL: https://habit.plgn.xyz
    labels:
      traefik.enable: true
      traefik.http.routers.habit_tracker.entrypoints: http
      traefik.http.routers.habit_tracker.rule: Host(`habit.plgn.xyz`)
      traefik.http.middlewares.habit_tracker-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.habit_tracker.middlewares: habit_tracker-https-redirect
      traefik.http.routers.habit_tracker-secure.entrypoints: https
      traefik.http.routers.habit_tracker-secure.rule: Host(`habit.plgn.xyz`)
      traefik.http.routers.habit_tracker-secure.tls: true
      traefik.http.routers.habit_tracker-secure.service: habit_tracker
      traefik.http.services.habit_tracker.loadbalancer.server.port: 3000
      traefik.docker.network: proxy

volumes:
  mysql: ~

networks:
  proxy:
    external: true
