import type { NextPage } from "next";
import Head from "next/head";
import { inferQueryOutput, trpc } from "@app/utils/trpc";
import { Calendar } from "@app/components/Calendar";

export type HabitWithLogs = inferQueryOutput<"habit.getBySlug">["habit"];

const Home: NextPage = () => {
  const { data } = trpc.useQuery([
    "habit.getBySlug",
    { slug: "strength-workout" },
  ]);

  if (!data || !data.habit) return null;

  return (
    <>
      <Head>
        <title>Habit Tracker App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <Calendar habit={data.habit} />
      </main>
    </>
  );
};

export default Home;
